apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-simple-pod
  labels:
    name: kubernetes-simple-pod
spec:
  containers:
  - name: kubernetes-simple-pod
    image: arisu1000/simple-container-app:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    env:
      - name: TESTENV01
        value: "testvalue01"
      - name: HOSTNAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: CPU_REQUEST
        valueFrom:
          resourceFieldRef:
            resource: requests.cpu
            containerName: kubernetes-simple-pod
      - name: CPU_LIMIT
        valueFrom:
          resourceFieldRef:
            resource: limits.cpu
            containerName: kubernetes-simple-pod
